name: TelegramConsoleBot
version: 2.0
main: com.grifmcpo.consolebot.TelegramConsoleBot
api-version: 1.21
author: GrifMcPo
description: Бот для управления сервером через Telegram

commands:
  pex:
    description: Информация об игроке
    usage: /pex user <ник>
    permission: pex.use
    aliases: [playerinfo, info]

permissions:
  pex.use:
    description: Доступ к команде /pex
    default: op
